#!/bin/sh

dump () {
    hexdump | cut -f2- -d ' ' | sed '$d'
}

echo "unsigned char* ${1:?argument needed} = {"

printf '\t'

dump | while read -r line; do
    for word in $line; do
        printf "0x${word%??},"
        printf "0x${word#??},"
    done
done

printf '\n};\n'
